Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,29 +16,39 @@ on:
           - development
 
 jobs:
-#  validate-branch:
-#    runs-on: ${{ vars.RUNNER }}
-#    outputs:
-#      is_valid: ${{ steps.check-branch.outputs.is_valid }}
-#    steps:
-#      - name: Validate release branch
-#        id: check-branch
-#        run: |
-#          if [[ "${GITHUB_EVENT_INPUTS_RELEASE_BRANCH}" =~ ^release\/.* ]]; then
-#            echo "is_valid=true" >> $GITHUB_ENV
-#          else
-#            echo "is_valid=false" >> $GITHUB_ENV
-#            echo "::error::The release branch must start with 'release/'"
-#           exit 1
-#         fi
+  validate-branch:
+    runs-on: ${{ vars.RUNNER }}
+    outputs:
+      is_valid: ${{ steps.check-branch.outputs.is_valid }}
+    steps:
+      - name: Validate release branch
+        id: check-branch
+        run: |
+          if [[ "${{ github.event.inputs.release_branch }}" =~ ^release\/.* ]]; then
+            echo "is_valid=true" >> $GITHUB_ENV
+          else
+            echo "is_valid=false" >> $GITHUB_ENV
+            echo "::error::The release branch must start with 'release/'"
+            exit 1
+          fi
  
   display-variables:
     name: Check Variables and Secrets
     runs-on: ${{ vars.RUNNER }}
-    #needs: validate-branch
-    #if: needs.validate-branch.outputs.is_valid == 'true'
+    needs: validate-branch
+    if: needs.validate-branch.outputs.is_valid == 'true'
     environment: ${{ github.event.inputs.environment }}  # User selects the environment
     steps:
-    - name: Show me the money!
-      run: |
-        echo "Variable: ${{ vars.VARIABLE }}"      
+      - name: Checkout the release branch
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.release_branch }}
+
+      # Add your steps to run the workflow here
+      - name: Show environment
+        run: |
+          echo "Environment: ${{ github.event.inputs.environment }}"
+
+      - name: Show variables
+        run: | 
+          echo "Variable: ${{ vars.VARIABLE }}"   
