Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,21 +16,23 @@ on:
           - development
 
 jobs:
-  validate-branch:
-    runs-on: ${{ vars.RUNNER }}
-    outputs:
-      is_valid: ${{ steps.check-branch.outputs.is_valid }}
-    steps:
-      - name: Validate release branch
-        id: check-branch
-        run: |
-          if [[ "${GITHUB_EVENT_INPUTS_RELEASE_BRANCH}" =~ ^release\/.* ]]; then
-            echo "is_valid=true" >> $GITHUB_ENV
-          else
-            echo "is_valid=false" >> $GITHUB_ENV
-            echo "::error::The release branch must start with 'release/'"
-            exit 1
-          fi
+
+#  validate-branch:
+#    runs-on: ${{ vars.RUNNER }}
+#    outputs:
+#      is_valid: ${{ steps.check-branch.outputs.is_valid }}
+#    steps:
+#      - name: Validate release branch
+#        id: check-branch
+#        run: |
+#          if [[ "${GITHUB_EVENT_INPUTS_RELEASE_BRANCH}" =~ ^release\/.* ]]; then
+#            echo "is_valid=true" >> $GITHUB_ENV
+#          else
+#            echo "is_valid=false" >> $GITHUB_ENV
+#            echo "::error::The release branch must start with 'release/'"
+#           exit 1
+#         fi
+ 
   display-variables:
     name: Check Variables and Secrets
     runs-on: ${{ vars.RUNNER }}
